### ISSUE TITLE
KeyMaster invisible in ElvUI Databar after game reload

### ISSUE THREAD

**Issue by Floppy012** [Puresyn/KeyMaster#52]
**Describe the bug**
*I'm writing this issue on behalf of my friend as their English skills aren't good enough to create an issue.*

Adding KeyMaster to the ElvUI Databar Minimap Panel only lasts until the next reload of the game.

**To Reproduce**

1.  Go to ElvUI settings
2. Datatext
3. Minimap Panels
4. Configure KeyMaster to show
![image](https://github.com/user-attachments/assets/081d66a2-8054-485a-b212-baf4569d313c)
5. Observe KeyMaster showing in the Databar
![image](https://github.com/user-attachments/assets/0c95f93b-81c2-41c5-b009-9be59c22d628)
6. Reload the game `/reload`
7. Observe KeyMaster missing
![image](https://github.com/user-attachments/assets/bf6c4eba-861c-407a-b7c1-18842db9dd23)

**Expected behavior**
KeyMaster should still be visible in the Databar after reloading the game. My friend has tried the same with DBM and it stays visible after the reload.

**Additional context**
~~I'm currently trying to guide them through the process of using BugSack and BugGrabber to maybe get some stacktraces.~~ BugSack/BugGrabber do not collect any related error while reloading. I'm personally not using ElvUI so I couldn't try to reproduce it myself.

**Comment by Puresyn** [comment]
Thank you for the report. We'll have a look!

**Comment by jcorrington** [comment]
@Floppy012 Thanks for bringing this to our attention.  Sadly we don't fully support integrations with other addons, especially since there is no error messages, but we can definitely try a few things to see if we can figure out a resolution for you! 

I do not use ElvUI myself either, so reproducing it might prove difficult.  

**Lets start by trying to recreate the KeyMaster database...**
Can you have them simply remove the local database file "KeyMaster.lua" found in "C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\<YOURACCOUNTNAME>\SavedVariables".  If you rename it or delete it and close and reopen the game does it fix the issue? 

_Please be aware deleting this fille will remove any stored data for the addon, which will require to login/logout of characters to repopulate._

**Comment by Floppy012** [comment]
Sadly it didn't work. Oh and it has absolutely no priority. It's just a convenience thing he wanted to mention to you guys :D

**Comment by Puresyn** [comment]
Thank you for brining this to our attention. If time permits in the future, perhaps we can look into supporting it.
